// 📝 Problem: Count and Say
// The Count and Say sequence is a series of numbers where each term is constructed by reading the previous term aloud.

// You start with: "1"

// The next term is generated by describing the previous term:

// Count how many times a digit appears consecutively, then say the count followed by the digit.
// n | Count and Say Output
// 1 | "1"
// 2 | "11"
// 3 | "21"
// 4 | "1211"
// 5 | "111221"

#include <iostream>
#include <string>
using namespace std;

string countAndSay(int n) {
    if(n == 1) return "1";
    if(n == 2) return "11";

    string s = "11";
    for(int i = 3; i <= n; i++) {
        string t = "";
        int count = 1;

        for(int j = 1; j < s.size(); j++) {
            if(s[j] != s[j - 1]) {
                t += to_string(count);
                t += s[j - 1];
                count = 1;
            } else {
                count++;
            }
        }

        t += to_string(count);
        t += s.back();
        s = t;
    }

    return s;
}

int main() {
    int n;
    cout << "Enter value of n: ";
    cin >> n;

    string result = countAndSay(n);
    cout << "The " << n << "th term in the Count and Say sequence is: " << result << endl;

    return 0;
}
